var ccb_resources = [
    {type:'effect', src:"error.mp3"},
    {type:'effect', src:"main.mp3"},
    {type:'effect', src:"mainBg.mp3"},
    {type:'effect', src:"menu.mp3"},
    {type:'effect', src:"Openning.mp3"},
    {type:'effect', src:"pop.mp3"},

    {type:'ccbi', src:"AboutScene.ccbi"},
    {type:'ccbi', src:"CFSGamePlayScene.ccbi"},
    {type:'ccbi', src:"HelpScene.ccbi"},
    {type:'ccbi', src:"HighScoreScene.ccbi"},
    {type:'ccbi', src:"LevelSelectScene.ccbi"},
    {type:'ccbi', src:"MainMenuScene.ccbi"},
    {type:'ccbi', src:"OpenningTitle-en.ccbi"},
    {type:'ccbi', src:"OpenningTitle-ja.ccbi"},
    {type:'ccbi', src:"OpenningTitle-zh.ccbi"},
    {type:'ccbi', src:"OptionLayer.ccbi"},
    {type:'ccbi', src:"GameWinLayer.ccbi"},
    {type:'ccbi', src:"GameLoseLayer.ccbi"},
    {type:'ccbi', src:"PauseLayer.ccbi"},
    {type:'ccbi', src:"ReadySetGo.ccbi"},

    {type:'plist', src:"element.plist"},
    {type:'plist', src:"paigow.plist"},
    {type:'plist', src:"tutorial.plist"},

    {type:'image', src:"splashTitle.png"},
    {type:'image', src:"about-zh.png"},
    {type:'image', src:"about-en.png"},
    {type:'image', src:"about-ja.png"},
    
    {type:'image', src:"element.png"},
    {type:'image', src:"mainBg.png"},
    {type:'image', src:"paigow.png"},
    {type:'image', src:"tableBg1.jpg"},
    {type:'image', src:"tableBg2.jpg"},
    {type:'image', src:"tableBg3.jpg"},
    {type:'image', src:"tableBg4.jpg"},
    {type:'image', src:"tableBg5.jpg"},
    {type:'image', src:"tutorial.png"}
];
